name: run EC2 command using SSM
on:
  push:

env:
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Run EC2 command using SSM
        id: exec-ec2-command
        run: |
            aws ssm send-command \
              --document-name "AWS-RunShellScript" \
              --instance-ids "i-0c5f0371cb89a850d" \
              --parameters commands=["sudo echo hello world > /tmp/test.txt"] \
              --output text \
              --query "Command.CommandId"
